// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: orchestrator.proto

package orchestrator

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TrainingJobRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	JobId           string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ModelType       string                 `protobuf:"bytes,3,opt,name=model_type,json=modelType,proto3" json:"model_type,omitempty"`
	DatasetPath     string                 `protobuf:"bytes,4,opt,name=dataset_path,json=datasetPath,proto3" json:"dataset_path,omitempty"`
	Hyperparameters map[string]string      `protobuf:"bytes,5,rep,name=hyperparameters,proto3" json:"hyperparameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	NumWorkers      int32                  `protobuf:"varint,6,opt,name=num_workers,json=numWorkers,proto3" json:"num_workers,omitempty"`
	Epochs          int32                  `protobuf:"varint,7,opt,name=epochs,proto3" json:"epochs,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TrainingJobRequest) Reset() {
	*x = TrainingJobRequest{}
	mi := &file_orchestrator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainingJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainingJobRequest) ProtoMessage() {}

func (x *TrainingJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainingJobRequest.ProtoReflect.Descriptor instead.
func (*TrainingJobRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{0}
}

func (x *TrainingJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *TrainingJobRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TrainingJobRequest) GetModelType() string {
	if x != nil {
		return x.ModelType
	}
	return ""
}

func (x *TrainingJobRequest) GetDatasetPath() string {
	if x != nil {
		return x.DatasetPath
	}
	return ""
}

func (x *TrainingJobRequest) GetHyperparameters() map[string]string {
	if x != nil {
		return x.Hyperparameters
	}
	return nil
}

func (x *TrainingJobRequest) GetNumWorkers() int32 {
	if x != nil {
		return x.NumWorkers
	}
	return 0
}

func (x *TrainingJobRequest) GetEpochs() int32 {
	if x != nil {
		return x.Epochs
	}
	return 0
}

type TrainingJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	NumTasks      int32                  `protobuf:"varint,3,opt,name=num_tasks,json=numTasks,proto3" json:"num_tasks,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrainingJobResponse) Reset() {
	*x = TrainingJobResponse{}
	mi := &file_orchestrator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainingJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainingJobResponse) ProtoMessage() {}

func (x *TrainingJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainingJobResponse.ProtoReflect.Descriptor instead.
func (*TrainingJobResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{1}
}

func (x *TrainingJobResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *TrainingJobResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TrainingJobResponse) GetNumTasks() int32 {
	if x != nil {
		return x.NumTasks
	}
	return 0
}

func (x *TrainingJobResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetJobStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobStatusRequest) Reset() {
	*x = GetJobStatusRequest{}
	mi := &file_orchestrator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobStatusRequest) ProtoMessage() {}

func (x *GetJobStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobStatusRequest.ProtoReflect.Descriptor instead.
func (*GetJobStatusRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{2}
}

func (x *GetJobStatusRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type GetJobStatusResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	JobId           string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status          string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Progress        int32                  `protobuf:"varint,3,opt,name=progress,proto3" json:"progress,omitempty"`
	CompletedTasks  int32                  `protobuf:"varint,4,opt,name=completed_tasks,json=completedTasks,proto3" json:"completed_tasks,omitempty"`
	TotalTasks      int32                  `protobuf:"varint,5,opt,name=total_tasks,json=totalTasks,proto3" json:"total_tasks,omitempty"`
	CurrentLoss     float64                `protobuf:"fixed64,6,opt,name=current_loss,json=currentLoss,proto3" json:"current_loss,omitempty"`
	CurrentAccuracy float64                `protobuf:"fixed64,7,opt,name=current_accuracy,json=currentAccuracy,proto3" json:"current_accuracy,omitempty"`
	Message         string                 `protobuf:"bytes,8,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetJobStatusResponse) Reset() {
	*x = GetJobStatusResponse{}
	mi := &file_orchestrator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobStatusResponse) ProtoMessage() {}

func (x *GetJobStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobStatusResponse.ProtoReflect.Descriptor instead.
func (*GetJobStatusResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{3}
}

func (x *GetJobStatusResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *GetJobStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetJobStatusResponse) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *GetJobStatusResponse) GetCompletedTasks() int32 {
	if x != nil {
		return x.CompletedTasks
	}
	return 0
}

func (x *GetJobStatusResponse) GetTotalTasks() int32 {
	if x != nil {
		return x.TotalTasks
	}
	return 0
}

func (x *GetJobStatusResponse) GetCurrentLoss() float64 {
	if x != nil {
		return x.CurrentLoss
	}
	return 0
}

func (x *GetJobStatusResponse) GetCurrentAccuracy() float64 {
	if x != nil {
		return x.CurrentAccuracy
	}
	return 0
}

func (x *GetJobStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AssignTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignTaskRequest) Reset() {
	*x = AssignTaskRequest{}
	mi := &file_orchestrator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignTaskRequest) ProtoMessage() {}

func (x *AssignTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignTaskRequest.ProtoReflect.Descriptor instead.
func (*AssignTaskRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{4}
}

func (x *AssignTaskRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

type AssignTaskResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TaskId          string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	JobId           string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	ModelType       string                 `protobuf:"bytes,3,opt,name=model_type,json=modelType,proto3" json:"model_type,omitempty"`
	DatasetPath     string                 `protobuf:"bytes,4,opt,name=dataset_path,json=datasetPath,proto3" json:"dataset_path,omitempty"`
	Hyperparameters map[string]string      `protobuf:"bytes,5,rep,name=hyperparameters,proto3" json:"hyperparameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Epoch           int32                  `protobuf:"varint,6,opt,name=epoch,proto3" json:"epoch,omitempty"`
	BatchStart      int32                  `protobuf:"varint,7,opt,name=batch_start,json=batchStart,proto3" json:"batch_start,omitempty"`
	BatchEnd        int32                  `protobuf:"varint,8,opt,name=batch_end,json=batchEnd,proto3" json:"batch_end,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AssignTaskResponse) Reset() {
	*x = AssignTaskResponse{}
	mi := &file_orchestrator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignTaskResponse) ProtoMessage() {}

func (x *AssignTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignTaskResponse.ProtoReflect.Descriptor instead.
func (*AssignTaskResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{5}
}

func (x *AssignTaskResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *AssignTaskResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *AssignTaskResponse) GetModelType() string {
	if x != nil {
		return x.ModelType
	}
	return ""
}

func (x *AssignTaskResponse) GetDatasetPath() string {
	if x != nil {
		return x.DatasetPath
	}
	return ""
}

func (x *AssignTaskResponse) GetHyperparameters() map[string]string {
	if x != nil {
		return x.Hyperparameters
	}
	return nil
}

func (x *AssignTaskResponse) GetEpoch() int32 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *AssignTaskResponse) GetBatchStart() int32 {
	if x != nil {
		return x.BatchStart
	}
	return 0
}

func (x *AssignTaskResponse) GetBatchEnd() int32 {
	if x != nil {
		return x.BatchEnd
	}
	return 0
}

type TaskCompletionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	JobId         string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	WorkerId      string                 `protobuf:"bytes,3,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Loss          float64                `protobuf:"fixed64,6,opt,name=loss,proto3" json:"loss,omitempty"`
	Accuracy      float64                `protobuf:"fixed64,7,opt,name=accuracy,proto3" json:"accuracy,omitempty"`
	ModelWeights  []byte                 `protobuf:"bytes,8,opt,name=model_weights,json=modelWeights,proto3" json:"model_weights,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskCompletionRequest) Reset() {
	*x = TaskCompletionRequest{}
	mi := &file_orchestrator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskCompletionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskCompletionRequest) ProtoMessage() {}

func (x *TaskCompletionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskCompletionRequest.ProtoReflect.Descriptor instead.
func (*TaskCompletionRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{6}
}

func (x *TaskCompletionRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskCompletionRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *TaskCompletionRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *TaskCompletionRequest) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TaskCompletionRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *TaskCompletionRequest) GetLoss() float64 {
	if x != nil {
		return x.Loss
	}
	return 0
}

func (x *TaskCompletionRequest) GetAccuracy() float64 {
	if x != nil {
		return x.Accuracy
	}
	return 0
}

func (x *TaskCompletionRequest) GetModelWeights() []byte {
	if x != nil {
		return x.ModelWeights
	}
	return nil
}

type TaskCompletionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskCompletionResponse) Reset() {
	*x = TaskCompletionResponse{}
	mi := &file_orchestrator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskCompletionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskCompletionResponse) ProtoMessage() {}

func (x *TaskCompletionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskCompletionResponse.ProtoReflect.Descriptor instead.
func (*TaskCompletionResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{7}
}

func (x *TaskCompletionResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *TaskCompletionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type JobMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Epoch         int32                  `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Loss          float64                `protobuf:"fixed64,3,opt,name=loss,proto3" json:"loss,omitempty"`
	Accuracy      float64                `protobuf:"fixed64,4,opt,name=accuracy,proto3" json:"accuracy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobMetricsRequest) Reset() {
	*x = JobMetricsRequest{}
	mi := &file_orchestrator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobMetricsRequest) ProtoMessage() {}

func (x *JobMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobMetricsRequest.ProtoReflect.Descriptor instead.
func (*JobMetricsRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{8}
}

func (x *JobMetricsRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobMetricsRequest) GetEpoch() int32 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *JobMetricsRequest) GetLoss() float64 {
	if x != nil {
		return x.Loss
	}
	return 0
}

func (x *JobMetricsRequest) GetAccuracy() float64 {
	if x != nil {
		return x.Accuracy
	}
	return 0
}

type JobMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobMetricsResponse) Reset() {
	*x = JobMetricsResponse{}
	mi := &file_orchestrator_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobMetricsResponse) ProtoMessage() {}

func (x *JobMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobMetricsResponse.ProtoReflect.Descriptor instead.
func (*JobMetricsResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{9}
}

func (x *JobMetricsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CancelJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelJobRequest) Reset() {
	*x = CancelJobRequest{}
	mi := &file_orchestrator_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelJobRequest) ProtoMessage() {}

func (x *CancelJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelJobRequest.ProtoReflect.Descriptor instead.
func (*CancelJobRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{10}
}

func (x *CancelJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type CancelJobResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	PreviousStatus string                 `protobuf:"bytes,3,opt,name=previous_status,json=previousStatus,proto3" json:"previous_status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CancelJobResponse) Reset() {
	*x = CancelJobResponse{}
	mi := &file_orchestrator_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelJobResponse) ProtoMessage() {}

func (x *CancelJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelJobResponse.ProtoReflect.Descriptor instead.
func (*CancelJobResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{11}
}

func (x *CancelJobResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelJobResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CancelJobResponse) GetPreviousStatus() string {
	if x != nil {
		return x.PreviousStatus
	}
	return ""
}

type WorkerActivityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerActivityRequest) Reset() {
	*x = WorkerActivityRequest{}
	mi := &file_orchestrator_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerActivityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerActivityRequest) ProtoMessage() {}

func (x *WorkerActivityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerActivityRequest.ProtoReflect.Descriptor instead.
func (*WorkerActivityRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{12}
}

type WorkerActivityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workers       []*WorkerInfo          `protobuf:"bytes,1,rep,name=workers,proto3" json:"workers,omitempty"`
	TotalWorkers  int32                  `protobuf:"varint,2,opt,name=total_workers,json=totalWorkers,proto3" json:"total_workers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerActivityResponse) Reset() {
	*x = WorkerActivityResponse{}
	mi := &file_orchestrator_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerActivityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerActivityResponse) ProtoMessage() {}

func (x *WorkerActivityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerActivityResponse.ProtoReflect.Descriptor instead.
func (*WorkerActivityResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{13}
}

func (x *WorkerActivityResponse) GetWorkers() []*WorkerInfo {
	if x != nil {
		return x.Workers
	}
	return nil
}

func (x *WorkerActivityResponse) GetTotalWorkers() int32 {
	if x != nil {
		return x.TotalWorkers
	}
	return 0
}

type WorkerInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	WorkerId         string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Status           string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	CurrentTaskId    string                 `protobuf:"bytes,3,opt,name=current_task_id,json=currentTaskId,proto3" json:"current_task_id,omitempty"`
	CurrentJobId     string                 `protobuf:"bytes,4,opt,name=current_job_id,json=currentJobId,proto3" json:"current_job_id,omitempty"`
	TasksCompleted   int32                  `protobuf:"varint,5,opt,name=tasks_completed,json=tasksCompleted,proto3" json:"tasks_completed,omitempty"`
	LastActivityTime int64                  `protobuf:"varint,6,opt,name=last_activity_time,json=lastActivityTime,proto3" json:"last_activity_time,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *WorkerInfo) Reset() {
	*x = WorkerInfo{}
	mi := &file_orchestrator_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerInfo) ProtoMessage() {}

func (x *WorkerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerInfo.ProtoReflect.Descriptor instead.
func (*WorkerInfo) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{14}
}

func (x *WorkerInfo) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *WorkerInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WorkerInfo) GetCurrentTaskId() string {
	if x != nil {
		return x.CurrentTaskId
	}
	return ""
}

func (x *WorkerInfo) GetCurrentJobId() string {
	if x != nil {
		return x.CurrentJobId
	}
	return ""
}

func (x *WorkerInfo) GetTasksCompleted() int32 {
	if x != nil {
		return x.TasksCompleted
	}
	return 0
}

func (x *WorkerInfo) GetLastActivityTime() int64 {
	if x != nil {
		return x.LastActivityTime
	}
	return 0
}

var File_orchestrator_proto protoreflect.FileDescriptor

const file_orchestrator_proto_rawDesc = "" +
	"\n" +
	"\x12orchestrator.proto\x12\forchestrator\"\xe4\x02\n" +
	"\x12TrainingJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"model_type\x18\x03 \x01(\tR\tmodelType\x12!\n" +
	"\fdataset_path\x18\x04 \x01(\tR\vdatasetPath\x12_\n" +
	"\x0fhyperparameters\x18\x05 \x03(\v25.orchestrator.TrainingJobRequest.HyperparametersEntryR\x0fhyperparameters\x12\x1f\n" +
	"\vnum_workers\x18\x06 \x01(\x05R\n" +
	"numWorkers\x12\x16\n" +
	"\x06epochs\x18\a \x01(\x05R\x06epochs\x1aB\n" +
	"\x14HyperparametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"{\n" +
	"\x13TrainingJobResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1b\n" +
	"\tnum_tasks\x18\x03 \x01(\x05R\bnumTasks\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\",\n" +
	"\x13GetJobStatusRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\x93\x02\n" +
	"\x14GetJobStatusResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1a\n" +
	"\bprogress\x18\x03 \x01(\x05R\bprogress\x12'\n" +
	"\x0fcompleted_tasks\x18\x04 \x01(\x05R\x0ecompletedTasks\x12\x1f\n" +
	"\vtotal_tasks\x18\x05 \x01(\x05R\n" +
	"totalTasks\x12!\n" +
	"\fcurrent_loss\x18\x06 \x01(\x01R\vcurrentLoss\x12)\n" +
	"\x10current_accuracy\x18\a \x01(\x01R\x0fcurrentAccuracy\x12\x18\n" +
	"\amessage\x18\b \x01(\tR\amessage\"0\n" +
	"\x11AssignTaskRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\"\xff\x02\n" +
	"\x12AssignTaskResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12\x1d\n" +
	"\n" +
	"model_type\x18\x03 \x01(\tR\tmodelType\x12!\n" +
	"\fdataset_path\x18\x04 \x01(\tR\vdatasetPath\x12_\n" +
	"\x0fhyperparameters\x18\x05 \x03(\v25.orchestrator.AssignTaskResponse.HyperparametersEntryR\x0fhyperparameters\x12\x14\n" +
	"\x05epoch\x18\x06 \x01(\x05R\x05epoch\x12\x1f\n" +
	"\vbatch_start\x18\a \x01(\x05R\n" +
	"batchStart\x12\x1b\n" +
	"\tbatch_end\x18\b \x01(\x05R\bbatchEnd\x1aB\n" +
	"\x14HyperparametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf8\x01\n" +
	"\x15TaskCompletionRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12\x1b\n" +
	"\tworker_id\x18\x03 \x01(\tR\bworkerId\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\x12\x12\n" +
	"\x04loss\x18\x06 \x01(\x01R\x04loss\x12\x1a\n" +
	"\baccuracy\x18\a \x01(\x01R\baccuracy\x12#\n" +
	"\rmodel_weights\x18\b \x01(\fR\fmodelWeights\"V\n" +
	"\x16TaskCompletionResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"p\n" +
	"\x11JobMetricsRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\x05R\x05epoch\x12\x12\n" +
	"\x04loss\x18\x03 \x01(\x01R\x04loss\x12\x1a\n" +
	"\baccuracy\x18\x04 \x01(\x01R\baccuracy\".\n" +
	"\x12JobMetricsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\")\n" +
	"\x10CancelJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"p\n" +
	"\x11CancelJobResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12'\n" +
	"\x0fprevious_status\x18\x03 \x01(\tR\x0epreviousStatus\"\x17\n" +
	"\x15WorkerActivityRequest\"q\n" +
	"\x16WorkerActivityResponse\x122\n" +
	"\aworkers\x18\x01 \x03(\v2\x18.orchestrator.WorkerInfoR\aworkers\x12#\n" +
	"\rtotal_workers\x18\x02 \x01(\x05R\ftotalWorkers\"\xe6\x01\n" +
	"\n" +
	"WorkerInfo\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12&\n" +
	"\x0fcurrent_task_id\x18\x03 \x01(\tR\rcurrentTaskId\x12$\n" +
	"\x0ecurrent_job_id\x18\x04 \x01(\tR\fcurrentJobId\x12'\n" +
	"\x0ftasks_completed\x18\x05 \x01(\x05R\x0etasksCompleted\x12,\n" +
	"\x12last_activity_time\x18\x06 \x01(\x03R\x10lastActivityTime2\xff\x04\n" +
	"\x13OrchestratorService\x12X\n" +
	"\x11CreateTrainingJob\x12 .orchestrator.TrainingJobRequest\x1a!.orchestrator.TrainingJobResponse\x12U\n" +
	"\fGetJobStatus\x12!.orchestrator.GetJobStatusRequest\x1a\".orchestrator.GetJobStatusResponse\x12O\n" +
	"\n" +
	"AssignTask\x12\x1f.orchestrator.AssignTaskRequest\x1a .orchestrator.AssignTaskResponse\x12a\n" +
	"\x14ReportTaskCompletion\x12#.orchestrator.TaskCompletionRequest\x1a$.orchestrator.TaskCompletionResponse\x12U\n" +
	"\x10UpdateJobMetrics\x12\x1f.orchestrator.JobMetricsRequest\x1a .orchestrator.JobMetricsResponse\x12L\n" +
	"\tCancelJob\x12\x1e.orchestrator.CancelJobRequest\x1a\x1f.orchestrator.CancelJobResponse\x12^\n" +
	"\x11GetWorkerActivity\x12#.orchestrator.WorkerActivityRequest\x1a$.orchestrator.WorkerActivityResponseB8Z6github.com/tensorfleet/orchestrator/proto/orchestratorb\x06proto3"

var (
	file_orchestrator_proto_rawDescOnce sync.Once
	file_orchestrator_proto_rawDescData []byte
)

func file_orchestrator_proto_rawDescGZIP() []byte {
	file_orchestrator_proto_rawDescOnce.Do(func() {
		file_orchestrator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orchestrator_proto_rawDesc), len(file_orchestrator_proto_rawDesc)))
	})
	return file_orchestrator_proto_rawDescData
}

var file_orchestrator_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_orchestrator_proto_goTypes = []any{
	(*TrainingJobRequest)(nil),     // 0: orchestrator.TrainingJobRequest
	(*TrainingJobResponse)(nil),    // 1: orchestrator.TrainingJobResponse
	(*GetJobStatusRequest)(nil),    // 2: orchestrator.GetJobStatusRequest
	(*GetJobStatusResponse)(nil),   // 3: orchestrator.GetJobStatusResponse
	(*AssignTaskRequest)(nil),      // 4: orchestrator.AssignTaskRequest
	(*AssignTaskResponse)(nil),     // 5: orchestrator.AssignTaskResponse
	(*TaskCompletionRequest)(nil),  // 6: orchestrator.TaskCompletionRequest
	(*TaskCompletionResponse)(nil), // 7: orchestrator.TaskCompletionResponse
	(*JobMetricsRequest)(nil),      // 8: orchestrator.JobMetricsRequest
	(*JobMetricsResponse)(nil),     // 9: orchestrator.JobMetricsResponse
	(*CancelJobRequest)(nil),       // 10: orchestrator.CancelJobRequest
	(*CancelJobResponse)(nil),      // 11: orchestrator.CancelJobResponse
	(*WorkerActivityRequest)(nil),  // 12: orchestrator.WorkerActivityRequest
	(*WorkerActivityResponse)(nil), // 13: orchestrator.WorkerActivityResponse
	(*WorkerInfo)(nil),             // 14: orchestrator.WorkerInfo
	nil,                            // 15: orchestrator.TrainingJobRequest.HyperparametersEntry
	nil,                            // 16: orchestrator.AssignTaskResponse.HyperparametersEntry
}
var file_orchestrator_proto_depIdxs = []int32{
	15, // 0: orchestrator.TrainingJobRequest.hyperparameters:type_name -> orchestrator.TrainingJobRequest.HyperparametersEntry
	16, // 1: orchestrator.AssignTaskResponse.hyperparameters:type_name -> orchestrator.AssignTaskResponse.HyperparametersEntry
	14, // 2: orchestrator.WorkerActivityResponse.workers:type_name -> orchestrator.WorkerInfo
	0,  // 3: orchestrator.OrchestratorService.CreateTrainingJob:input_type -> orchestrator.TrainingJobRequest
	2,  // 4: orchestrator.OrchestratorService.GetJobStatus:input_type -> orchestrator.GetJobStatusRequest
	4,  // 5: orchestrator.OrchestratorService.AssignTask:input_type -> orchestrator.AssignTaskRequest
	6,  // 6: orchestrator.OrchestratorService.ReportTaskCompletion:input_type -> orchestrator.TaskCompletionRequest
	8,  // 7: orchestrator.OrchestratorService.UpdateJobMetrics:input_type -> orchestrator.JobMetricsRequest
	10, // 8: orchestrator.OrchestratorService.CancelJob:input_type -> orchestrator.CancelJobRequest
	12, // 9: orchestrator.OrchestratorService.GetWorkerActivity:input_type -> orchestrator.WorkerActivityRequest
	1,  // 10: orchestrator.OrchestratorService.CreateTrainingJob:output_type -> orchestrator.TrainingJobResponse
	3,  // 11: orchestrator.OrchestratorService.GetJobStatus:output_type -> orchestrator.GetJobStatusResponse
	5,  // 12: orchestrator.OrchestratorService.AssignTask:output_type -> orchestrator.AssignTaskResponse
	7,  // 13: orchestrator.OrchestratorService.ReportTaskCompletion:output_type -> orchestrator.TaskCompletionResponse
	9,  // 14: orchestrator.OrchestratorService.UpdateJobMetrics:output_type -> orchestrator.JobMetricsResponse
	11, // 15: orchestrator.OrchestratorService.CancelJob:output_type -> orchestrator.CancelJobResponse
	13, // 16: orchestrator.OrchestratorService.GetWorkerActivity:output_type -> orchestrator.WorkerActivityResponse
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_orchestrator_proto_init() }
func file_orchestrator_proto_init() {
	if File_orchestrator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orchestrator_proto_rawDesc), len(file_orchestrator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orchestrator_proto_goTypes,
		DependencyIndexes: file_orchestrator_proto_depIdxs,
		MessageInfos:      file_orchestrator_proto_msgTypes,
	}.Build()
	File_orchestrator_proto = out.File
	file_orchestrator_proto_goTypes = nil
	file_orchestrator_proto_depIdxs = nil
}
